version: '3'
services:
  db:
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: root
    ports:
      - "5432:5432"
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/runlog
    ports:
      - "3000:3000"
    depends_on:
      - db
